### ISSUE TITLE
Markdown plugin and empty paragraphs

### ISSUE THREAD

**Issue by tmpfs** [reshape/content#14]
When I use the syntax:

```
p(md) *Markdown*
```

I end up with a paragraph (`<p>`) beforehand consisting of whitespace and an empty paragraph afterwards (no text content). These extraneous elements are wreaking havoc with my styles and are not welcome!

I am sure you can come up with a much better solution but for the moment I have hacked it with:

```javascript
if(node.name === 'p' && key === 'md') {
  return node.content;
}
```

After the line:

```javascript
node.content = parser(res.join(''), {}, opts)
```

The reason I think is that we are using an outer `p` element in the reshape markup and markdown will always wrap freeform text into it's own paragraph so we end up with nested paragraphs which I believe is invalid HTML, hence the strange rendering issue.

I will leave the hack in my local version because this problem needs to be fixed urgently for me, but would love to find a more *correct* (and permanent) solution to the problem.

Still enjoying reshape :)

**Comment by jescalan** [comment]
Hi there! Good news, this is easily solveable. The issue actually comes from `standard`, since there's no predefined `md` function here in `content`. The issue stems from [this line](https://github.com/reshape/standard/blob/master/lib/index.js#L37), where it binds the `md` function to `render` on markdownIt. The `render` function will render full markdown, headlines, code blocks, etc and also paragraphs for text with line breaks in between. If you are looking to render just one bit of info, you can use the `renderInline` function.

Sorry this hasn't been previously fixed, I just haven't had a minute recently. The fix should be to export `md` and `md-inline`, which are bound to their respective functions, then you'd be able to use the inline function which won't wrap with an additional paragraph.

**Comment by tmpfs** [comment]
Great, thanks for the heads up. I was looking at that line but couldn't see an issue with it, now I know there is a `renderInline` function the solution you propose seems fairly trivial.

I will take a look at it some more tomorrow and see if I can come up with a solution worthy of a PR.

Ta!

**Comment by jescalan** [comment]
Just published a fix for this, upgrade `reshape-standard` for the fix!

https://github.com/reshape/standard#markdown-rendering-functions

**Comment by tmpfs** [comment]
Very neat and fast - thank you :)

**Comment by tmpfs** [comment]
Tested and working great with the latest `reshape-standard` - awesome!

**Comment by jescalan** [comment]
🎉
