### ISSUE TITLE
__runtime.escape(), markdown not parsed

### ISSUE THREAD

**Issue by aaditya-madala** [reshape/content#19]
Hello! I am not sure if this is the right place to raise this issue since the project environment is a spike project, with contentful plugin, and reshape content parser. I think it might be since the doubt is concerning the output of the reshape and markdown-it integration.

In my page I have the following expressions:

```
<p>{{item.fields.body}}</p>
<div md>{{item.fields.body}}</div>
```

I get the following output:

```
__Markdown__ *content*

__runtime.escape(item.fields.body)

```

The markdown content is being displayed as is when it is not parsed as markdown in a <p> tag in the first line. However, in the second line I get the __runtime.escape output when I try to parse the markdown content. What is the error here?

Thank you!

**Comment by jescalan** [comment]
Hi @aaditya-madala!

So this is a common issue, and I probably should add it to the [faqs](https://spike.readme.io/docs/faqs) honestly. But this is how its supposed to work.

When you compile your html, this happens at _compile time_. That is, the html is parsed by [reshape's](https://github.com/reshape/reshape#usage) plugins and turned into a javascript function. It does not know what values any variables will hold, because the variables are injected at _runtime_. So when you pull down contentful data, it is piped into your templates as variables, which must be evaluated at runtime.

In the context of spike, this isn't entirely obvious, since for static views, compile time and runtime happen back to back. BUT it's important that this distinction is here because you can compile a single template both as html and as a client side javascript function with spike, which is an important capability for more dynamic sites.

The solution is simply adding a markdown parser as a local. So adding any markdown parser to your `locals` object that is passed into reshape, then passing your contentful data through it, will do the trick. For example:

```js
// app.js
const marked = require('marked')
// ...
reshape: () => {
  return htmlStandards({
    locals: { md: marked }
  })
}
// ...
```

```jade
p {{ md(item.fields.body) }}
```

Hope this makes sense! Let me know if you are having any other issues 😁

**Comment by aaditya-madala** [comment]
Thank you very much for the detailed explanation @jescalan! I followed your suggestion and added the markdown parser to the locals and also made sure to use [unescapedDelimiters](https://github.com/reshape/expressions#unescaped-locals)
`{{{ md(item.fields.body) }}}` to parse the md() return value as html.

**Comment by jescalan** [comment]
That should do it! Sorry I forgot to mention the unescape delimiters in my previous response, but I'm glad you got it working! Feel free to drop by our [friendly community chatroom](https://gitter.im/static-dev/spike) anytime too if you want to talk about what you're building and/or get support 😁
