### ISSUE TITLE
Overwrite marked.Renderer image function

### ISSUE THREAD

**Issue by mkaag** [reshape/content#41]
Hello,

this echos #19, where I thought I could find a solution to my pb, which it did partially.
I would like to pipe data from Contentful (using spike-contentful) and filter the potential images from the body in order to replace the *image* tag with some picturefill (multiple img tag with various media set).

Back to *roots.cx*, I was able to do the following from a helper file named *helpers/md-image.js*:

```
var marked = require('marked');
var renderer = new marked.Renderer();

renderer.image = function (href, title, text) {
    // process html here
    return processedHtml
};

module.exports = renderer;
```

When needed, I would simply call `!= marked(entry.content, { renderer: renderer })`

Following #19, I set my helper file in *app.js* such as:

```
const renderer = require('./helpers/md-image')
locals.md = renderer
```

and later in my template `p {{{ md(item.fields.content) }}}`
which ends up with the error `ModuleBuildError: Module build failed: TypeError: md is not a function`

Is there a way I could overwrite `renderer.image()` just like I did for *roots.cx* and apply the new function for reshape-content to pick up?

Thank you in advance for your answer!

**Comment by jescalan** [comment]
So the way you call it here is totally different. As you said yourself, in roots, you would call `marked(xxx, { renderer })` - this worked because `marked` is a function, and you passed the renderer as an option. In this case, you are replacing `marked` entirely with a renderer - you do this when you do `locals.md = renderer`. The renderer is not a function, it's a class, so its no surprise that it gives you the "not a function" error when you try to call it as a function.

What you'd have to do instead is call it the same way - use the marked function, but pass in the renderer as an option. So perhaps something like this:

```
locals.renderer = renderer
```

then

```
{{{ md(item.fields.content, { renderer }) }}}
```

Does that make sense?

**Comment by mkaag** [comment]
Hi @jescalan, thank you for taking the time to answer.

It does totally make sense, I've updated the template accordingly and added the below to `app.js`- otherwise I end up with the same error :-)

```
const marked = require('marked')
locals.md = marked
```

Spike rocks and the time you spent explaining those details make it even better!

**Comment by jescalan** [comment]
Awesome, I'm so glad this worked out and that you are enjoying spike! 👬
