### ISSUE TITLE
Block Content within markdown does not render

### ISSUE THREAD

**Issue by hhsnopek** [reshape/content#6]
Neither of these examples render markdown

```
.content(md)
  # Header One
  ## my list
   - item 1
   - item 2

.content(md)
  | # Header One
  | ## my list
  | - item 1
  | - item 2
```

**Comment by jescalan** [comment]
So this is actually an issue with the way that the markdown example is given. `renderInline` only does some selective elements, where `render` does them all and will render this out correctly.

With the pipe syntax, each line is represented as a separate text node, so things like that list won't render correctly, and each item will be wrapped by a `ul`, since they are each processed independently.

If you want to have them all processed together you can use the block content syntax with sugarml, as such:

``` jade
.content(md).
  # Header One
  ## my list
   - item 1
   - item 2
```

I updated the readme to reflect this change, and added some test coverage for these two cases 😁
